dubbo.scan.base-packages=com.battcn.book.provider.service
dubbo.application.id=battcn-provider-book
dubbo.application.name=battcn-provider-book
dubbo.application.qos-port=10051
dubbo.application.qos-enable=true
dubbo.registry.address=N/A
dubbo.registry.id=my-registry
dubbo.protocol.id=dubbo
dubbo.protocol.name=dubbo
dubbo.protocol.port=20882
dubbo.protocol.status=server
dubbo.provider.timeout=5000