spring:
  profiles:
    active: sharding-tables
management:
  health:
    db:
      enabled: false
security:
  oauth2:
    client:
      client-secret: client
      client-id: client
      scope: server
      grant-type: client_credentials,password
      access-token-uri: http://wemirr-platform-authority/oauth/token
      ignore:
        resource-urls:
          - /oauth/**
          - /bury/actuator/**
          - /bury/favicon.ico
          - /bury/swagger-ui/**
          - /swagger-resources
          - /swagger-resources/**
          - /v2/api-docs
    resource:
      # 这个地方如果不是同一个注册容器，则不用开启
      loadBalanced: true
      token-info-uri: http://wemirr-platform-authority/oauth/check_token
      prefer-token-info: false
      user-info-uri: http://wemirr-platform-authority/oauth/users