server:
  port: 8085
spring:
  application:
    name: battcn-consumer-management
  profiles:
    active: dev
  swagger:
    base-package: com.battcn
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/  
    suffix: .html
dubbo:
  application:
    id: battcn-consumer-management
    name: battcn-consumer-management
    qos-port: 22223
  consumer:
    timeout: 10000
endpoints:
  dubbo:
    enabled: true

---
# 开发环境
spring:
  profiles: dev
template-storage-path: D:/html/
template-domain-name: file:///${template-storage-path}

---
# Linux部署环境
spring:
  profiles: prod
template-storage-path: /data/battcn3.0/template/
template-domain-name: http://book.battcn.com/template/