CREATE TABLE `bms_order_receivable` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `order_id` bigint NOT NULL DEFAULT '0' COMMENT '订单ID(tms_order.id)',
  `payer_id` bigint DEFAULT '0' COMMENT '付款方公司ID(tms_company.id)',
  `payer_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '付款方公司(tms_company.name)',
  `payee_id` bigint DEFAULT '0' COMMENT '收款方公司ID(tms_company.id)',
  `payee_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '收款方公司(tms_company.name)',
  `fee_type` int NOT NULL DEFAULT '0' COMMENT '费用类型ID(dic_fee_type.id)',
  `fee_amount` decimal(20,2) DEFAULT '0.00' COMMENT '金额',
  `currency_type` int DEFAULT '0' COMMENT '币种ID(dic_currency_type.id)',
  `operator_id` bigint DEFAULT '0' COMMENT '操作人员ID(user.id)',
  `remark` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '节点备注',
  `rule_id` bigint DEFAULT NULL COMMENT '计费规则ID(bms_rule.id)',
  `sku_id` bigint DEFAULT NULL COMMENT '订单货物ID(tms_order_sku.id)',
  `station_id` bigint DEFAULT NULL COMMENT '站点ID(tms_station.id)',
  `task_id` bigint DEFAULT NULL COMMENT '任务ID(tms_task.id)',
  `source_id` int DEFAULT '0' COMMENT '数据来源(dic_source.id)',
  `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否启用 0=未锁定 1=锁定(逻辑删除用)',
  `created_by` bigint NOT NULL COMMENT '创建人ID',
  `created_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '创建人名称',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_modified_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `last_modified_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `last_modified_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `or_order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单应收费用表';