CREATE TABLE `tms_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
  `task_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '调度计划名称',
  `task_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '调度号',
  `project_id` bigint NOT NULL COMMENT '项目id(dic_project.id)',
  `transport_type` int NOT NULL DEFAULT '0' COMMENT '运输方式(dic_transport_type.id)',
  `truck_type` int DEFAULT NULL COMMENT '车辆类型ID(dic_truck_type.id)',
  `etd` datetime DEFAULT NULL COMMENT '预计提货时间',
  `atd` datetime DEFAULT NULL COMMENT '实际提货时间',
  `eta` datetime DEFAULT NULL COMMENT '预计到达时间',
  `ata` datetime DEFAULT NULL COMMENT '实际到达时间',
  `station_from` bigint DEFAULT NULL COMMENT '始发站点ID',
  `station_to` bigint DEFAULT NULL COMMENT '目的站点ID',
  `driver_id` bigint DEFAULT NULL COMMENT '司机ID(tms_driver.id)',
  `driver_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '司机姓名(tms_driver.name)',
  `driver_mobile` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '司机手机号(tms_driver.mobile)',
  `truck_id` bigint DEFAULT NULL COMMENT '车辆id(tms_truck.id)',
  `plate_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '车牌号(tms_truck.plate_number)',
  `remark` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '任务备注',
  `task_status` int NOT NULL DEFAULT '0' COMMENT '订单状态:-10取消,0新建,10出发,20运输中,30到达,40完成',
  `source_id` int DEFAULT '0' COMMENT '数据来源(dic_source.id)',
  `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否启用 0=未锁定 1=锁定(逻辑删除用)',
  `created_by` bigint NOT NULL COMMENT '创建人ID',
  `created_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '创建人名称',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_modified_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `last_modified_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `last_modified_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `tt_task_no` (`task_no`) USING BTREE,
  KEY `tt_project_id` (`project_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='调度计划表';