CREATE TABLE `tms_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `system_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '平台单号,系统生成',
  `order_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客户运单号',
  `waybill_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运输单号',
  `project_id` bigint NOT NULL COMMENT '项目id(dic_project.id)',
  `project_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '项目名称(dic_project.name)',
  `transport_type` int NOT NULL DEFAULT '0' COMMENT '运输方式(dic_transport_type.id)',
  `cargo_desc` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '货物信息',
  `quantity` int NOT NULL DEFAULT '0' COMMENT '总数量',
  `detail_quantity` int DEFAULT '0' COMMENT '订单明细数量',
  `gross_weight` decimal(20,5) DEFAULT '0.00000' COMMENT '毛重',
  `volume` decimal(20,5) DEFAULT '0.00000' COMMENT '体积',
  `check_quantity` int DEFAULT '0' COMMENT '确认数量',
  `check_weight` decimal(20,5) DEFAULT '0.00000' COMMENT '确认重量',
  `check_volume` decimal(20,5) DEFAULT '0.00000' COMMENT '确认体积',
  `declare_value` decimal(20,2) DEFAULT '0.00' COMMENT '声明价值',
  `etd` datetime DEFAULT NULL COMMENT '预计发货时间',
  `atd` datetime DEFAULT NULL COMMENT '实际发货时间',
  `eta` datetime DEFAULT NULL COMMENT '预计到达时间',
  `ata` datetime DEFAULT NULL COMMENT '实际到达时间',
  `pick_time` datetime DEFAULT NULL COMMENT '提货时间',
  `pod_time` datetime DEFAULT NULL COMMENT '签收时间',
  `latest_event_type` int DEFAULT '0' COMMENT '最后一个节点类型(dic_event_type.id)',
  `latest_event_id` bigint DEFAULT NULL COMMENT '最后一个节点id(tms_order_event.id)',
  `order_status` int NOT NULL DEFAULT '0' COMMENT '订单状态:-10取消,0新建,10提货,20到达始发站,30离开始发站,40到达目的站,50离开目的站,60签收,70回单,80完成',
  `remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单备注',
  `operator_id` bigint DEFAULT '0' COMMENT '操作人员ID(user.id)',
  `transport_line_id` bigint DEFAULT '0' COMMENT '运输线路id(tms_transport_line.id)',
  `has_epod` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '是否有电子回单',
  `source_id` int DEFAULT '0' COMMENT '数据来源(dic_source.id)',
  `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否启用 0=未锁定 1=锁定(逻辑删除用)',
  `created_by` bigint NOT NULL COMMENT '创建人ID',
  `created_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '创建人名称',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_modified_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `last_modified_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `last_modified_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `oo_system_no` (`system_no`) USING BTREE,
  KEY `oo_order_no` (`order_no`) USING BTREE,
  KEY `oo_waybill_no` (`waybill_no`) USING BTREE,
  KEY `oo_operator_id` (`operator_id`) USING BTREE,
  KEY `oo_project_id` (`project_id`) USING BTREE,
  KEY `oo_latest_event_type` (`latest_event_type`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单表';