CREATE TABLE `tms_order_sku` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `order_id` bigint NOT NULL COMMENT '订单ID(tms_order.id)',
  `sku_master_id` bigint DEFAULT NULL COMMENT '货物规格id(dic_sku_master.id)',
  `item_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '货号',
  `box_no` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '箱号',
  `cargo_desc` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '货物信息',
  `al` decimal(20,2) DEFAULT NULL COMMENT '长',
  `aw` decimal(20,2) DEFAULT NULL COMMENT '宽',
  `ah` decimal(20,2) DEFAULT NULL COMMENT '高',
  `quantity` int DEFAULT NULL COMMENT '数量',
  `weight` decimal(20,5) DEFAULT NULL COMMENT '毛重',
  `volume` decimal(20,5) DEFAULT NULL COMMENT '体积',
  `qty_unit` int DEFAULT NULL COMMENT '单位',
  `remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '货物备注',
  `check_quantity` int DEFAULT '0' COMMENT '确认数量',
  `check_weight` decimal(20,5) DEFAULT '0.00000' COMMENT '确认重量',
  `check_volume` decimal(20,5) DEFAULT '0.00000' COMMENT '确认体积',
  `source_id` int DEFAULT '0' COMMENT '数据来源(dic_source.id)',
  `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否启用 0=未锁定 1=锁定(逻辑删除用)',
  `created_by` bigint NOT NULL COMMENT '创建人ID',
  `created_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '创建人名称',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_modified_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `last_modified_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `last_modified_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `osku_order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单货物明细表';