CREATE TABLE `tms_order_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `order_id` bigint NOT NULL DEFAULT '0' COMMENT '订单ID(tms_order.id)',
  `system_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '平台单号(tms_order.system_number)',
  `province` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '省份',
  `city` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '城市',
  `district` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '区县',
  `longitude` decimal(20,6) DEFAULT '0.000000' COMMENT '经度',
  `latitude` decimal(20,6) DEFAULT '0.000000' COMMENT '纬度',
  `record_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录时间',
  `event_type` int NOT NULL DEFAULT '0' COMMENT '节点状态ID(dic_event_type.id)',
  `operator_id` bigint DEFAULT '0' COMMENT '操作人员ID(user.id)',
  `remark` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '节点备注',
  `quantity` int NOT NULL DEFAULT '0' COMMENT '总数量',
  `gross_weight` decimal(20,5) DEFAULT '0.00000' COMMENT '毛重',
  `volume` decimal(20,5) DEFAULT '0.00000' COMMENT '体积',
  `sku_id` bigint DEFAULT NULL COMMENT '订单货物ID(tms_order_sku.id)',
  `station_id` bigint DEFAULT NULL COMMENT '站点ID(tms_station.id)',
  `task_id` bigint DEFAULT NULL COMMENT '任务ID(tms_task.id)',
  `driver_id` bigint DEFAULT NULL COMMENT '司机ID(tms_driver.id)',
  `driver_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '司机姓名(tms_driver.name)',
  `driver_mobile` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '司机手机号(tms_driver.mobile)',
  `truck_id` bigint DEFAULT NULL COMMENT '车辆id(tms_truck.id)',
  `plate_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '车牌号(tms_truck.plate_number)',
  `source_id` int DEFAULT '0' COMMENT '数据来源(dic_source.id)',
  `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否启用 0=未锁定 1=锁定(逻辑删除用)',
  `created_by` bigint NOT NULL COMMENT '创建人ID',
  `created_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '创建人名称',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_modified_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `last_modified_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
  `last_modified_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `event_order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单节点表';