server:
  port: 9090
spring:
  application:
    name: battcn-bookstore-consumer
  swagger:
    base-package: com.battcn
    global-operation-parameters:
    -   description: 'Token信息,非必填项'
        modelRef: 'string'
        name: 'X-Authorization'
        parameter-type: 'header'
        required: false
  redis:
    battcn:
      cache:
        db: 0
      lock:
        db: 1
      sequence:
        db: 2
        profile: dev
      limit:
        db: 3
    timeout: 10000
    pool:
      min-idle: 10
      max-active: 200
      max-idle: 100
      max-wait: 1000
    password: battcn
  security:
    battcn:
      token:
        expiration-time: 1024
        refresh-exp-time: 2048
        issuer: http://battcn.com
        signing-key: battcn
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.0.134:9300
  mvc:
    exception:
      enabled: true
      default-message: 服务繁忙,请稍后再试
      expose-error-class: true

management:
  port: 9091
  health:
    db:
      enabled: false
    dubbo:
      status:
        defaults: memory
dubbo:
  application:
    id: battcn-management-consumer
    name: battcn-management-consumer
    qos-port: 22223
endpoints:
  dubbo:
    enabled: true