dubbo.scan.base-packages=com.battcn.member.provider.service
dubbo.application.id=battcn-provider-member
dubbo.application.name=battcn-provider-member
dubbo.application.qos-port=10041
dubbo.application.qos-enable=true
dubbo.registry.id=registry-battcn-provider-member
dubbo.registry.address=zookeeper://localhost:2181
dubbo.protocol.id=dubbo
dubbo.protocol.name=dubbo
dubbo.protocol.port=20881
dubbo.protocol.status=server
dubbo.provider.timeout=5000