server:
  port: 5001
spring:
  application:
    name: wemirr-platform-tools
  config:
    import:
      - optional:nacos:cloud-default.yaml
      - optional:nacos:${spring.application.name}.properties
      - optional:nacos:mybatis-plus-default.yaml?group=DEFAULT_GROUP&refreshEnabled=true #这是完写法
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848