server:
  port: 9090
spring:
  profiles:
    active: dubbo
  application:
    name: battcn-consumer-bookstore
  swagger:
    base-package: com.battcn
    global-operation-parameters:
    -   description: 'Token信息,非必填项'
        modelRef: 'string'
        name: 'X-Authorization'
        parameter-type: 'header'
        required: false
  redis:
    battcn:
      cache:
        db: 0
      lock:
        db: 0
      sequence:
        db: 0
        profile: dev
      limit:
        db: 0
    timeout: 10000
    password: battcn
    host: localhost
    port: 6389
  security:
    battcn:
      token:
        expiration-time: 43200
        refresh-exp-time: 86400
        issuer: http://battcn.com
        signing-key: battcn
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.0.134:9300
  mvc:
    exception:
      enabled: true
      default-message: 服务繁忙,请稍后再试
      expose-error-class: true