server:
  port: 10060
spring:
  profiles:
    active: dubbo
  application:
    name: battcn-provider-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300

logging:
  level:
    com.battcn: DEBUG
